# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Theme Settings
minimal_mistakes_skin    : "default" # Skin options: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "AI and AT Blog"
title_separator          : "-"
description              : "A blog to understand AI and Assistive Technology."
url                      : "https://stu2454.github.io"
baseurl                  : "/AIAssist"
repository               : "stu2454/AIAssist"

# Site Author
author:
  name             : "Stuart Smith PhD MSc"
  bio              : "Interested in all things tech and accessibility"
  location         : "Bellingen"
  email            : "stuart.smith@ndis.gov.au"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stu2454"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stu2454"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

# Conversion
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Sidebar Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      sidebar:
        - title: "About Me"
          text: "Stuart Smith PhD MSc<br>Interested in all things tech and accessibility"
        - title: "Contact"
          text: |
            Email: <a href="mailto:stuart.smith@ndis.gov.au">stuart.smith@ndis.gov.au</a><br>
            Location: Bellingen
        - title: "Recent Posts"
          nav: "recent_posts"

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"

collections:
  posts:
    output: true
    permalink: /:title/

