# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      sidebar:
        - title: "About Me"
          text: "Stuart Smith PhD MSc<br>Interested in all things tech and accessibility"
        - title: "Contact"
          text: |
            Email: <a href="mailto:stuart.smith@ndis.gov.au">stuart.smith@ndis.gov.au</a><br>
            Location: Bellingen
        - title: "Recent Posts"
          nav: "recent_posts"

#navigation
navigation:
  - main

# Sidebar for navigation
author:
  name             : "Stuart Smith PhD MSc"
  # avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Interested in all things tech and accessibility"
  location         : "Bellingen"
  email            : "stuart.smith@ndis.gov.au"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:stuart.smith@ndis.gov.au"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stu2454"

