title: "AI & Assistive Technology"
email: "stuart.smith@ndis.gov.au"
description: "Exploring the intersection of AI and assistive technology."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stu2454.github.io" # the base hostname & protocol for your site
lang: "en-AU"

# Social media and web presence links
author:
  name: "Stuart Smith PhD MSc"
  # avatar: "/assets/images/bio-photo.jpg"
  bio: "Interested in all things tech and accessibility"
  location: "Bellingen"
  email: "stuart.smith@ndis.gov.au"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:stuart.smith@ndis.gov.au"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stu2454"

# Defaults for pages, posts, and collections
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        - title: "About Me"
          text: "Stuart Smith PhD MSc<br>Interested in all things tech and accessibility"
        - title: "Contact"
          text: |
            Email: <a href="mailto:stuart.smith@ndis.gov.au">stuart.smith@ndis.gov.au</a><br>
            Location: Bellingen
        - title: "Recent Posts"
          nav: "recent_posts"

# Markdown settings
markdown: kramdown
highlighter: rouge

# Theme and plugins
theme: "minimal-mistakes-jekyll"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Navigation menu
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"
  - title: "GitHub"
    url: "https://github.com/stu2454"

# Sidebar and widgets
sidebar:
  nav: "main"

# Taxonomies
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

categories:
  - AI
  - Assistive Technology
  - Accessibility
tags:
  - AI
  - Disability
  - NDIS
  - Accessibility
  - Technology

# SEO and meta settings
google_analytics: "UA-XXXXXX-X" # Replace with your Google Analytics ID
sitemap:
  changefreq: "weekly"
  priority: 0.5
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Other settings
future: true
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true
  auto_ids: true
  toc_levels: 1..6
  hard_wrap: false

